/* eslint-disable */
/**
 * This file was automatically generated by @algorandfoundation/algokit-client-generator.
 * DO NOT MODIFY IT BY HAND.
 * requires: @algorandfoundation/algokit-utils: ^7
 */
import { type AlgorandClient } from '@algorandfoundation/algokit-utils/types/algorand-client'
import { ABIReturn, AppReturn, SendAppTransactionResult } from '@algorandfoundation/algokit-utils/types/app'
import { Arc56Contract, getArc56ReturnValue, getABIStructFromABITuple } from '@algorandfoundation/algokit-utils/types/app-arc56'
import {
  AppClient as _AppClient,
  AppClientMethodCallParams,
  AppClientParams,
  AppClientBareCallParams,
  CallOnComplete,
  AppClientCompilationParams,
  ResolveAppClientByCreatorAndName,
  ResolveAppClientByNetwork,
  CloneAppClientParams,
} from '@algorandfoundation/algokit-utils/types/app-client'

import { TransactionComposer, AppCallMethodCall, AppMethodCallTransactionArgument, SimulateOptions, RawSimulateOptions, SkipSignaturesSimulateOptions } from '@algorandfoundation/algokit-utils/types/composer'
import { SendParams, SendSingleTransactionResult, SendAtomicTransactionComposerResults } from '@algorandfoundation/algokit-utils/types/transaction'
import { Address, encodeAddress, modelsv2, OnApplicationComplete, Transaction, TransactionSigner } from 'algosdk'

export const APP_SPEC: Arc56Contract = {"name":"ABITestShortTypeNotation","desc":"","methods":[{"name":"shortTypeNotation","args":[],"returns":{"type":"uint16"},"actions":{"create":[],"call":["NoOp"]}},{"name":"createApplication","args":[],"returns":{"type":"void"},"actions":{"create":["NoOp"],"call":[]}}],"arcs":[4,56],"structs":{},"state":{"schema":{"global":{"bytes":0,"ints":0},"local":{"bytes":0,"ints":0}},"keys":{"global":{},"local":{},"box":{}},"maps":{"global":{},"local":{},"box":{}}},"bareActions":{"create":[],"call":[]},"sourceInfo":{"approval":{"sourceInfo":[{"pc":[39],"errorMessage":"The requested action is not implemented in this contract. Are you using the correct OnComplete? Did you set your app ID?","teal":24},{"pc":[55],"errorMessage":"shortTypeNotation return value overflowed 16 bits","teal":40},{"pc":[120],"errorMessage":"this contract does not implement the given ABI method for create NoOp","teal":83},{"pc":[134],"errorMessage":"this contract does not implement the given ABI method for call NoOp","teal":91}],"pcOffsetMethod":"none"},"clear":{"sourceInfo":[],"pcOffsetMethod":"none"}}} as unknown as Arc56Contract

/**
 * A state record containing binary data
 */
export interface BinaryState {
  /**
   * Gets the state value as a Uint8Array
   */
  asByteArray(): Uint8Array | undefined
  /**
   * Gets the state value as a string
   */
  asString(): string | undefined
}

class BinaryStateValue implements BinaryState {
  constructor(private value: Uint8Array | undefined) {}

  asByteArray(): Uint8Array | undefined {
    return this.value
  }

  asString(): string | undefined {
    return this.value !== undefined ? Buffer.from(this.value).toString('utf-8') : undefined
  }
}

/**
 * Expands types for IntelliSense so they are more human readable
 * See https://stackoverflow.com/a/69288824
 */
export type Expand<T> = T extends (...args: infer A) => infer R
  ? (...args: Expand<A>) => Expand<R>
  : T extends infer O
    ? { [K in keyof O]: O[K] }
    : never


/**
 * The argument types for the AbiTestShortTypeNotation contract
 */
export type AbiTestShortTypeNotationArgs = {
  /**
   * The object representation of the arguments for each method
   */
  obj: {
    'shortTypeNotation()uint16': Record<string, never>
    'createApplication()void': Record<string, never>
  }
  /**
   * The tuple representation of the arguments for each method
   */
  tuple: {
    'shortTypeNotation()uint16': []
    'createApplication()void': []
  }
}

/**
 * The return type for each method
 */
export type AbiTestShortTypeNotationReturns = {
  'shortTypeNotation()uint16': number
  'createApplication()void': void
}

/**
 * Defines the types of available calls and state of the AbiTestShortTypeNotation smart contract.
 */
export type AbiTestShortTypeNotationTypes = {
  /**
   * Maps method signatures / names to their argument and return types.
   */
  methods:
    & Record<'shortTypeNotation()uint16' | 'shortTypeNotation', {
      argsObj: AbiTestShortTypeNotationArgs['obj']['shortTypeNotation()uint16']
      argsTuple: AbiTestShortTypeNotationArgs['tuple']['shortTypeNotation()uint16']
      returns: AbiTestShortTypeNotationReturns['shortTypeNotation()uint16']
    }>
    & Record<'createApplication()void' | 'createApplication', {
      argsObj: AbiTestShortTypeNotationArgs['obj']['createApplication()void']
      argsTuple: AbiTestShortTypeNotationArgs['tuple']['createApplication()void']
      returns: AbiTestShortTypeNotationReturns['createApplication()void']
    }>
}

/**
 * Defines the possible abi call signatures.
 */
export type AbiTestShortTypeNotationSignatures = keyof AbiTestShortTypeNotationTypes['methods']
/**
 * Defines the possible abi call signatures for methods that return a non-void value.
 */
export type AbiTestShortTypeNotationNonVoidMethodSignatures = keyof AbiTestShortTypeNotationTypes['methods'] extends infer T ? T extends keyof AbiTestShortTypeNotationTypes['methods'] ? MethodReturn<T> extends void ? never : T  : never : never
/**
 * Defines an object containing all relevant parameters for a single call to the contract.
 */
export type CallParams<TArgs> = Expand<
  Omit<AppClientMethodCallParams, 'method' | 'args' | 'onComplete'> &
    {
      /** The args for the ABI method call, either as an ordered array or an object */
      args: Expand<TArgs>
    }
>
/**
 * Maps a method signature from the AbiTestShortTypeNotation smart contract to the method's arguments in either tuple or struct form
 */
export type MethodArgs<TSignature extends AbiTestShortTypeNotationSignatures> = AbiTestShortTypeNotationTypes['methods'][TSignature]['argsObj' | 'argsTuple']
/**
 * Maps a method signature from the AbiTestShortTypeNotation smart contract to the method's return type
 */
export type MethodReturn<TSignature extends AbiTestShortTypeNotationSignatures> = AbiTestShortTypeNotationTypes['methods'][TSignature]['returns']



/**
 * Exposes methods for constructing `AppClient` params objects for ABI calls to the AbiTestShortTypeNotation smart contract
 */
export abstract class AbiTestShortTypeNotationParamsFactory {
  /**
   * Constructs a no op call for the shortTypeNotation()uint16 ABI method
   *
   * @param params Parameters for the call
   * @returns An `AppClientMethodCallParams` object for the call
   */
  static shortTypeNotation(params: CallParams<AbiTestShortTypeNotationArgs['obj']['shortTypeNotation()uint16'] | AbiTestShortTypeNotationArgs['tuple']['shortTypeNotation()uint16']> & CallOnComplete): AppClientMethodCallParams & CallOnComplete {
    return {
      ...params,
      method: 'shortTypeNotation()uint16' as const,
      args: Array.isArray(params.args) ? params.args : [],
    }
  }
}

/**
 * A client to make calls to the ABITestShortTypeNotation smart contract
 */
export class AbiTestShortTypeNotationClient {
  /**
   * The underlying `AppClient` for when you want to have more flexibility
   */
  public readonly appClient: _AppClient

  /**
   * Creates a new instance of `AbiTestShortTypeNotationClient`
   *
   * @param appClient An `AppClient` instance which has been created with the AbiTestShortTypeNotation app spec
   */
  constructor(appClient: _AppClient)
  /**
   * Creates a new instance of `AbiTestShortTypeNotationClient`
   *
   * @param params The parameters to initialise the app client with
   */
  constructor(params: Omit<AppClientParams, 'appSpec'>)
  constructor(appClientOrParams: _AppClient | Omit<AppClientParams, 'appSpec'>) {
    this.appClient = appClientOrParams instanceof _AppClient ? appClientOrParams : new _AppClient({
      ...appClientOrParams,
      appSpec: APP_SPEC,
    })
  }

  /**
   * Checks for decode errors on the given return value and maps the return value to the return type for the given method
   * @returns The typed return value or undefined if there was no value
   */
  decodeReturnValue<TSignature extends AbiTestShortTypeNotationNonVoidMethodSignatures>(method: TSignature, returnValue: ABIReturn | undefined) {
    return returnValue !== undefined ? getArc56ReturnValue<MethodReturn<TSignature>>(returnValue, this.appClient.getABIMethod(method), APP_SPEC.structs) : undefined
  }

  /**
   * Returns a new `AbiTestShortTypeNotationClient` client, resolving the app by creator address and name
   * using AlgoKit app deployment semantics (i.e. looking for the app creation transaction note).
   * @param params The parameters to create the app client
   */
  public static async fromCreatorAndName(params: Omit<ResolveAppClientByCreatorAndName, 'appSpec'>): Promise<AbiTestShortTypeNotationClient> {
    return new AbiTestShortTypeNotationClient(await _AppClient.fromCreatorAndName({...params, appSpec: APP_SPEC}))
  }
  
  /**
   * Returns an `AbiTestShortTypeNotationClient` instance for the current network based on
   * pre-determined network-specific app IDs specified in the ARC-56 app spec.
   *
   * If no IDs are in the app spec or the network isn't recognised, an error is thrown.
   * @param params The parameters to create the app client
   */
  static async fromNetwork(
    params: Omit<ResolveAppClientByNetwork, 'appSpec'>
  ): Promise<AbiTestShortTypeNotationClient> {
    return new AbiTestShortTypeNotationClient(await _AppClient.fromNetwork({...params, appSpec: APP_SPEC}))
  }
  
  /** The ID of the app instance this client is linked to. */
  public get appId() {
    return this.appClient.appId
  }
  
  /** The app address of the app instance this client is linked to. */
  public get appAddress() {
    return this.appClient.appAddress
  }
  
  /** The name of the app. */
  public get appName() {
    return this.appClient.appName
  }
  
  /** The ARC-56 app spec being used */
  public get appSpec() {
    return this.appClient.appSpec
  }
  
  /** A reference to the underlying `AlgorandClient` this app client is using. */
  public get algorand(): AlgorandClient {
    return this.appClient.algorand
  }

  /**
   * Get parameters to create transactions for the current app. A good mental model for this is that these parameters represent a deferred transaction creation.
   */
  readonly params = {
    /**
     * Makes a clear_state call to an existing instance of the ABITestShortTypeNotation smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams>) => {
      return this.appClient.params.bare.clearState(params)
    },

    /**
     * Makes a call to the ABITestShortTypeNotation smart contract using the `shortTypeNotation()uint16` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call params
     */
    shortTypeNotation: (params: CallParams<AbiTestShortTypeNotationArgs['obj']['shortTypeNotation()uint16'] | AbiTestShortTypeNotationArgs['tuple']['shortTypeNotation()uint16']> & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      return this.appClient.params.call(AbiTestShortTypeNotationParamsFactory.shortTypeNotation(params))
    },

  }

  /**
   * Create transactions for the current app
   */
  readonly createTransaction = {
    /**
     * Makes a clear_state call to an existing instance of the ABITestShortTypeNotation smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams>) => {
      return this.appClient.createTransaction.bare.clearState(params)
    },

    /**
     * Makes a call to the ABITestShortTypeNotation smart contract using the `shortTypeNotation()uint16` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call transaction
     */
    shortTypeNotation: (params: CallParams<AbiTestShortTypeNotationArgs['obj']['shortTypeNotation()uint16'] | AbiTestShortTypeNotationArgs['tuple']['shortTypeNotation()uint16']> & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      return this.appClient.createTransaction.call(AbiTestShortTypeNotationParamsFactory.shortTypeNotation(params))
    },

  }

  /**
   * Send calls to the current app
   */
  readonly send = {
    /**
     * Makes a clear_state call to an existing instance of the ABITestShortTypeNotation smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams & SendParams>) => {
      return this.appClient.send.bare.clearState(params)
    },

    /**
     * Makes a call to the ABITestShortTypeNotation smart contract using the `shortTypeNotation()uint16` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call result
     */
    shortTypeNotation: async (params: CallParams<AbiTestShortTypeNotationArgs['obj']['shortTypeNotation()uint16'] | AbiTestShortTypeNotationArgs['tuple']['shortTypeNotation()uint16']> & SendParams & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      const result = await this.appClient.send.call(AbiTestShortTypeNotationParamsFactory.shortTypeNotation(params))
      return {...result, return: result.return as unknown as (undefined | AbiTestShortTypeNotationReturns['shortTypeNotation()uint16'])}
    },

  }

  /**
   * Clone this app client with different params
   *
   * @param params The params to use for the the cloned app client. Omit a param to keep the original value. Set a param to override the original value. Setting to undefined will clear the original value.
   * @returns A new app client with the altered params
   */
  public clone(params: CloneAppClientParams) {
    return new AbiTestShortTypeNotationClient(this.appClient.clone(params))
  }

  /**
   * Methods to access state for the current ABITestShortTypeNotation app
   */
  state = {
  }

  public newGroup(): AbiTestShortTypeNotationComposer {
    const client = this
    const composer = this.algorand.newGroup()
    let promiseChain:Promise<unknown> = Promise.resolve()
    const resultMappers: Array<undefined | ((x: ABIReturn | undefined) => any)> = []
    return {
      /**
       * Add a shortTypeNotation()uint16 method call against the ABITestShortTypeNotation contract
       */
      shortTypeNotation(params: CallParams<AbiTestShortTypeNotationArgs['obj']['shortTypeNotation()uint16'] | AbiTestShortTypeNotationArgs['tuple']['shortTypeNotation()uint16']> & {onComplete?: OnApplicationComplete.NoOpOC}) {
        promiseChain = promiseChain.then(async () => composer.addAppCallMethodCall(await client.params.shortTypeNotation(params)))
        resultMappers.push((v) => client.decodeReturnValue('shortTypeNotation()uint16', v))
        return this
      },
      /**
       * Add a clear state call to the ABITestShortTypeNotation contract
       */
      clearState(params: AppClientBareCallParams) {
        promiseChain = promiseChain.then(() => composer.addAppCall(client.params.clearState(params)))
        return this
      },
      addTransaction(txn: Transaction, signer?: TransactionSigner) {
        promiseChain = promiseChain.then(() => composer.addTransaction(txn, signer))
        return this
      },
      async composer() {
        await promiseChain
        return composer
      },
      async simulate(options?: SimulateOptions) {
        await promiseChain
        const result = await (!options ? composer.simulate() : composer.simulate(options))
        return {
          ...result,
          returns: result.returns?.map((val, i) => resultMappers[i] !== undefined ? resultMappers[i]!(val) : val.returnValue)
        }
      },
      async send(params?: SendParams) {
        await promiseChain
        const result = await composer.send(params)
        return {
          ...result,
          returns: result.returns?.map((val, i) => resultMappers[i] !== undefined ? resultMappers[i]!(val) : val.returnValue)
        }
      }
    } as unknown as AbiTestShortTypeNotationComposer
  }
}
export type AbiTestShortTypeNotationComposer<TReturns extends [...any[]] = []> = {
  /**
   * Calls the shortTypeNotation()uint16 ABI method.
   *
   * @param args The arguments for the contract call
   * @param params Any additional parameters for the call
   * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
   */
  shortTypeNotation(params?: CallParams<AbiTestShortTypeNotationArgs['obj']['shortTypeNotation()uint16'] | AbiTestShortTypeNotationArgs['tuple']['shortTypeNotation()uint16']>): AbiTestShortTypeNotationComposer<[...TReturns, AbiTestShortTypeNotationReturns['shortTypeNotation()uint16'] | undefined]>

  /**
   * Makes a clear_state call to an existing instance of the ABITestShortTypeNotation smart contract.
   *
   * @param args The arguments for the bare call
   * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
   */
  clearState(params?: AppClientBareCallParams): AbiTestShortTypeNotationComposer<[...TReturns, undefined]>

  /**
   * Adds a transaction to the composer
   *
   * @param txn A transaction to add to the transaction group
   * @param signer The optional signer to use when signing this transaction.
   */
  addTransaction(txn: Transaction, signer?: TransactionSigner): AbiTestShortTypeNotationComposer<TReturns>
  /**
   * Returns the underlying AtomicTransactionComposer instance
   */
  composer(): Promise<TransactionComposer>
  /**
   * Simulates the transaction group and returns the result
   */
  simulate(): Promise<AbiTestShortTypeNotationComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  simulate(options: SkipSignaturesSimulateOptions): Promise<AbiTestShortTypeNotationComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  simulate(options: RawSimulateOptions): Promise<AbiTestShortTypeNotationComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  /**
   * Sends the transaction group to the network and returns the results
   */
  send(params?: SendParams): Promise<AbiTestShortTypeNotationComposerResults<TReturns>>
}
export type AbiTestShortTypeNotationComposerResults<TReturns extends [...any[]]> = Expand<SendAtomicTransactionComposerResults & {
  returns: TReturns
}>

