using System;
using Algorand;
using Algorand.Algod;
using Algorand.Algod.Model;
using Algorand.Algod.Model.Transactions;
using AVM.ClientGenerator;
using AVM.ClientGenerator.Core;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AVM.ClientGenerator.ABI.ARC56;
using Algorand.AVM.ClientGenerator.ABI.ARC56;

namespace Arc56.Generated.algorandfoundation.puya_ts.SingleEvalAlgo_20c9994c
{


    public class SingleEvalAlgoProxy : ProxyBase
    {
        public override AppDescriptionArc56 App { get; set; }

        public SingleEvalAlgoProxy(DefaultApi defaultApi, ulong appId) : base(defaultApi, appId)
        {
            App = Newtonsoft.Json.JsonConvert.DeserializeObject<AVM.ClientGenerator.ABI.ARC56.AppDescriptionArc56>(Encoding.UTF8.GetString(Convert.FromBase64String(_ARC56DATA))) ?? throw new Exception("Error reading ARC56 data");

        }

        public class Structs
        {
        }

        ///<summary>
        ///
        ///</summary>
        public async Task Test(Account _tx_sender, ulong? _tx_fee, string _tx_note = "", ulong _tx_roundValidity = 1000, List<BoxRef>? _tx_boxes = null, List<Transaction>? _tx_transactions = null, List<ulong>? _tx_assets = null, List<ulong>? _tx_apps = null, List<Address>? _tx_accounts = null, AVM.ClientGenerator.Core.OnCompleteType _tx_callType = AVM.ClientGenerator.Core.OnCompleteType.NoOp)
        {
            _tx_boxes ??= new List<BoxRef>();
            _tx_transactions ??= new List<Transaction>();
            _tx_assets ??= new List<ulong>();
            _tx_apps ??= new List<ulong>();
            _tx_accounts ??= new List<Address>();
            byte[] abiHandle = { 167, 128, 0, 222 };

            var result = await base.CallApp(new List<object> { abiHandle }, _tx_fee: _tx_fee, _tx_callType: _tx_callType, _tx_roundValidity: _tx_roundValidity, _tx_note: _tx_note, _tx_sender: _tx_sender, _tx_transactions: _tx_transactions, _tx_apps: _tx_apps, _tx_assets: _tx_assets, _tx_accounts: _tx_accounts, _tx_boxes: _tx_boxes);

        }

        public async Task<List<Transaction>> Test_Transactions(Account _tx_sender, ulong? _tx_fee, string _tx_note = "", ulong _tx_roundValidity = 1000, List<BoxRef>? _tx_boxes = null, List<Transaction>? _tx_transactions = null, List<ulong>? _tx_assets = null, List<ulong>? _tx_apps = null, List<Address>? _tx_accounts = null, AVM.ClientGenerator.Core.OnCompleteType _tx_callType = AVM.ClientGenerator.Core.OnCompleteType.NoOp)
        {
            _tx_boxes ??= new List<BoxRef>();
            _tx_transactions ??= new List<Transaction>();
            _tx_assets ??= new List<ulong>();
            _tx_apps ??= new List<ulong>();
            _tx_accounts ??= new List<Address>();
            byte[] abiHandle = { 167, 128, 0, 222 };

            return await base.MakeTransactionList(new List<object> { abiHandle }, _tx_fee: _tx_fee, _tx_callType: _tx_callType, _tx_roundValidity: _tx_roundValidity, _tx_note: _tx_note, _tx_sender: _tx_sender, _tx_transactions: _tx_transactions, _tx_apps: _tx_apps, _tx_assets: _tx_assets, _tx_accounts: _tx_accounts, _tx_boxes: _tx_boxes);

        }

        ///<summary>
        ///Constructor Bare Action
        ///</summary>
        public async Task CreateApplication(Account _tx_sender, ulong? _tx_fee, string _tx_note = "", ulong _tx_roundValidity = 1000, List<BoxRef>? _tx_boxes = null, List<Transaction>? _tx_transactions = null, List<ulong>? _tx_assets = null, List<ulong>? _tx_apps = null, List<Address>? _tx_accounts = null, AVM.ClientGenerator.Core.OnCompleteType _tx_callType = AVM.ClientGenerator.Core.OnCompleteType.CreateApplication)
        {
            _tx_boxes ??= new List<BoxRef>();
            _tx_transactions ??= new List<Transaction>();
            _tx_assets ??= new List<ulong>();
            _tx_apps ??= new List<ulong>();
            _tx_accounts ??= new List<Address>();
            byte[] abiHandle = { 0, 193, 250, 21 };

            var result = await base.CallApp(new List<object> { }, _tx_fee: _tx_fee, _tx_callType: _tx_callType, _tx_roundValidity: _tx_roundValidity, _tx_note: _tx_note, _tx_sender: _tx_sender, _tx_transactions: _tx_transactions, _tx_apps: _tx_apps, _tx_assets: _tx_assets, _tx_accounts: _tx_accounts, _tx_boxes: _tx_boxes);

        }

        public async Task<List<Transaction>> CreateApplication_Transactions(Account _tx_sender, ulong? _tx_fee, string _tx_note = "", ulong _tx_roundValidity = 1000, List<BoxRef>? _tx_boxes = null, List<Transaction>? _tx_transactions = null, List<ulong>? _tx_assets = null, List<ulong>? _tx_apps = null, List<Address>? _tx_accounts = null, AVM.ClientGenerator.Core.OnCompleteType _tx_callType = AVM.ClientGenerator.Core.OnCompleteType.CreateApplication)
        {
            _tx_boxes ??= new List<BoxRef>();
            _tx_transactions ??= new List<Transaction>();
            _tx_assets ??= new List<ulong>();
            _tx_apps ??= new List<ulong>();
            _tx_accounts ??= new List<Address>();
            byte[] abiHandle = { 0, 193, 250, 21 };

            return await base.MakeTransactionList(new List<object> { }, _tx_fee: _tx_fee, _tx_callType: _tx_callType, _tx_roundValidity: _tx_roundValidity, _tx_note: _tx_note, _tx_sender: _tx_sender, _tx_transactions: _tx_transactions, _tx_apps: _tx_apps, _tx_assets: _tx_assets, _tx_accounts: _tx_accounts, _tx_boxes: _tx_boxes);

        }

        protected override ulong? ExtraProgramPages { get; set; } = 0;
        protected string _ARC56DATA = "eyJhcmNzIjpbMjIsMjhdLCJuYW1lIjoiU2luZ2xlRXZhbEFsZ28iLCJkZXNjIjpudWxsLCJuZXR3b3JrcyI6e30sInN0cnVjdHMiOnt9LCJNZXRob2RzIjpbeyJuYW1lIjoidGVzdCIsImRlc2MiOm51bGwsImFyZ3MiOltdLCJyZXR1cm5zIjp7InR5cGUiOiJ2b2lkIiwic3RydWN0IjpudWxsLCJkZXNjIjpudWxsfSwiYWN0aW9ucyI6eyJjcmVhdGUiOltdLCJjYWxsIjpbIk5vT3AiXX0sInJlYWRvbmx5IjpmYWxzZSwiZXZlbnRzIjpbXSwicmVjb21tZW5kYXRpb25zIjp7ImlubmVyVHJhbnNhY3Rpb25Db3VudCI6bnVsbCwiYm94ZXMiOm51bGwsImFjY291bnRzIjpudWxsLCJhcHBzIjpudWxsLCJhc3NldHMiOm51bGx9fV0sInN0YXRlIjp7InNjaGVtYSI6eyJnbG9iYWwiOnsiaW50cyI6MSwiYnl0ZXMiOjB9LCJsb2NhbCI6eyJpbnRzIjowLCJieXRlcyI6MH19LCJrZXlzIjp7Imdsb2JhbCI6eyJkZXNjIjpudWxsLCJrZXlUeXBlIjoiIiwidmFsdWVUeXBlIjoiIiwia2V5IjoiIn0sImxvY2FsIjp7ImRlc2MiOm51bGwsImtleVR5cGUiOiIiLCJ2YWx1ZVR5cGUiOiIiLCJrZXkiOiIifSwiYm94Ijp7ImRlc2MiOm51bGwsImtleVR5cGUiOiIiLCJ2YWx1ZVR5cGUiOiIiLCJrZXkiOiIifX0sIm1hcHMiOnsiZ2xvYmFsIjp7ImRlc2MiOm51bGwsImtleVR5cGUiOiIiLCJ2YWx1ZVR5cGUiOiIiLCJwcmVmaXgiOm51bGx9LCJsb2NhbCI6eyJkZXNjIjpudWxsLCJrZXlUeXBlIjoiIiwidmFsdWVUeXBlIjoiIiwicHJlZml4IjpudWxsfSwiYm94Ijp7ImRlc2MiOm51bGwsImtleVR5cGUiOiIiLCJ2YWx1ZVR5cGUiOiIiLCJwcmVmaXgiOm51bGx9fX0sImJhcmVBY3Rpb25zIjp7ImNyZWF0ZSI6WyJOb09wIl0sImNhbGwiOltdfSwic291cmNlSW5mbyI6eyJhcHByb3ZhbCI6eyJzb3VyY2VJbmZvIjpbeyJwYyI6WzE1NV0sImVycm9yTWVzc2FnZSI6IlJlc3VsdCBzaG91bGQgYmUgXCJhXCIiLCJ0ZWFsIjpudWxsLCJzb3VyY2UiOm51bGx9LHsicGMiOlsxNTJdLCJlcnJvck1lc3NhZ2UiOiJhKCkgc2hvdWxkIG9ubHkgYmUgY2FsbGVkIG9uY2UiLCJ0ZWFsIjpudWxsLCJzb3VyY2UiOm51bGx9LHsicGMiOlsxMDAsMTQ5XSwiZXJyb3JNZXNzYWdlIjoiY2hlY2sgR2xvYmFsU3RhdGUgZXhpc3RzIiwidGVhbCI6bnVsbCwic291cmNlIjpudWxsfV0sInBjT2Zmc2V0TWV0aG9kIjoibm9uZSJ9LCJjbGVhciI6eyJzb3VyY2VJbmZvIjpbXSwicGNPZmZzZXRNZXRob2QiOiJub25lIn19LCJzb3VyY2UiOnsiYXBwcm92YWwiOiJJM0J5WVdkdFlTQjJaWEp6YVc5dUlERXhDaU53Y21GbmJXRWdkSGx3WlhSeVlXTnJJR1poYkhObENnb3ZMeUJBWVd4bmIzSmhibVJtYjNWdVpHRjBhVzl1TDJGc1oyOXlZVzVrTFhSNWNHVnpZM0pwY0hRdllYSmpOQzlwYm1SbGVDNWtMblJ6T2pwRGIyNTBjbUZqZEM1aGNIQnliM1poYkZCeWIyZHlZVzBvS1NBdFBpQjFhVzUwTmpRNkNtMWhhVzQ2Q2lBZ0lDQnBiblJqWW14dlkyc2dNQ0F4Q2lBZ0lDQmllWFJsWTJKc2IyTnJJQ0p0ZVZOMFlYUmxJaUFpWVNJS0lDQWdJR0lnYldGcGJsOWliRzlqYTBBd0NncHRZV2x1WDJKc2IyTnJRREE2Q2lBZ0lDQmlJRzFoYVc1ZllteHZZMnRBTVFvS2JXRnBibDlpYkc5amEwQXhPZ29nSUNBZ0x5OGdkR1Z6ZEhNdllYQndjbTkyWVd4ekwzTnBibWRzWlMxbGRtRnNMbUZzWjI4dWRITTZOQW9nSUNBZ0x5OGdZMnhoYzNNZ1UybHVaMnhsUlhaaGJFRnNaMjhnWlhoMFpXNWtjeUJEYjI1MGNtRmpkQ0I3Q2lBZ0lDQjBlRzRnVG5WdFFYQndRWEpuY3dvZ0lDQWdhVzUwWTE4d0lDOHZJREFLSUNBZ0lDRTlDaUFnSUNCaWVpQnRZV2x1WDE5ZllXeG5iM1J6WDE4dVpHVm1ZWFZzZEVOeVpXRjBaVUExQ2lBZ0lDQmlJRzFoYVc1ZllXSnBYM0p2ZFhScGJtZEFNZ29LYldGcGJsOWhZbWxmY205MWRHbHVaMEF5T2dvZ0lDQWdMeThnZEdWemRITXZZWEJ3Y205MllXeHpMM05wYm1kc1pTMWxkbUZzTG1Gc1oyOHVkSE02TkFvZ0lDQWdMeThnWTJ4aGMzTWdVMmx1WjJ4bFJYWmhiRUZzWjI4Z1pYaDBaVzVrY3lCRGIyNTBjbUZqZENCN0NpQWdJQ0IwZUc1aElFRndjR3hwWTJGMGFXOXVRWEpuY3lBd0NpQWdJQ0J3ZFhOb1lubDBaWE1nTUhoaE56Z3dNREJrWlNBdkx5QnRaWFJvYjJRZ0luUmxjM1FvS1hadmFXUWlDaUFnSUNCMWJtTnZkbVZ5SURFS0lDQWdJRzFoZEdOb0lHMWhhVzVmZEdWemRGOXliM1YwWlVBekNpQWdJQ0JpSUcxaGFXNWZjM2RwZEdOb1gyTmhjMlZmYm1WNGRFQTBDZ3B0WVdsdVgzTjNhWFJqYUY5allYTmxYMjVsZUhSQU5Eb0tJQ0FnSUdJZ2JXRnBibDloWm5SbGNsOXBabDlsYkhObFFEWUtDbTFoYVc1ZllXWjBaWEpmYVdaZlpXeHpaVUEyT2dvZ0lDQWdMeThnZEdWemRITXZZWEJ3Y205MllXeHpMM05wYm1kc1pTMWxkbUZzTG1Gc1oyOHVkSE02TkFvZ0lDQWdMeThnWTJ4aGMzTWdVMmx1WjJ4bFJYWmhiRUZzWjI4Z1pYaDBaVzVrY3lCRGIyNTBjbUZqZENCN0NpQWdJQ0JsY25JS0NtMWhhVzVmZEdWemRGOXliM1YwWlVBek9nb2dJQ0FnTHk4Z2RHVnpkSE12WVhCd2NtOTJZV3h6TDNOcGJtZHNaUzFsZG1Gc0xtRnNaMjh1ZEhNNk1UWUtJQ0FnSUM4dklIUmxjM1FvS1NCN0NpQWdJQ0IwZUc0Z1QyNURiMjF3YkdWMGFXOXVDaUFnSUNCcGJuUmpYekFnTHk4Z1RtOVBjQW9nSUNBZ1BUMEtJQ0FnSUhSNGJpQkJjSEJzYVdOaGRHbHZia2xFQ2lBZ0lDQnBiblJqWHpBZ0x5OGdNQW9nSUNBZ0lUMEtJQ0FnSUNZbUNpQWdJQ0JoYzNObGNuUUtJQ0FnSUdOaGJHeHpkV0lnZEdWemRBb2dJQ0FnWWlCdFlXbHVYM04zYVhSamFGOWpZWE5sWDI1bGVIUkFOQW9LYldGcGJsOWZYMkZzWjI5MGMxOWZMbVJsWm1GMWJIUkRjbVZoZEdWQU5Ub0tJQ0FnSUM4dklIUmxjM1J6TDJGd2NISnZkbUZzY3k5emFXNW5iR1V0WlhaaGJDNWhiR2R2TG5Sek9qUUtJQ0FnSUM4dklHTnNZWE56SUZOcGJtZHNaVVYyWVd4QmJHZHZJR1Y0ZEdWdVpITWdRMjl1ZEhKaFkzUWdld29nSUNBZ2RIaHVJRTl1UTI5dGNHeGxkR2x2YmdvZ0lDQWdhVzUwWTE4d0lDOHZJRTV2VDNBS0lDQWdJRDA5Q2lBZ0lDQjBlRzRnUVhCd2JHbGpZWFJwYjI1SlJBb2dJQ0FnYVc1MFkxOHdJQzh2SURBS0lDQWdJRDA5Q2lBZ0lDQW1KZ29nSUNBZ1lYTnpaWEowQ2lBZ0lDQmpZV3hzYzNWaUlGOWZZV3huYjNSelgxOHVaR1ZtWVhWc2RFTnlaV0YwWlFvZ0lDQWdhVzUwWTE4eElDOHZJREVLSUNBZ0lISmxkSFZ5YmdvS0NpOHZJSFJsYzNSekwyRndjSEp2ZG1Gc2N5OXphVzVuYkdVdFpYWmhiQzVoYkdkdkxuUnpPanBUYVc1bmJHVkZkbUZzUVd4bmJ5NTBaWE4wVzNKdmRYUnBibWRkS0NrZ0xUNGdkbTlwWkRvS2RHVnpkRG9LSUNBZ0lHSWdkR1Z6ZEY5aWJHOWphMEF3Q2dwMFpYTjBYMkpzYjJOclFEQTZDaUFnSUNBdkx5QjBaWE4wY3k5aGNIQnliM1poYkhNdmMybHVaMnhsTFdWMllXd3VZV3huYnk1MGN6b3hOZ29nSUNBZ0x5OGdkR1Z6ZENncElIc0tJQ0FnSUdOaGJHeHpkV0lnZEdWemRITXZZWEJ3Y205MllXeHpMM05wYm1kc1pTMWxkbUZzTG1Gc1oyOHVkSE02T2xOcGJtZHNaVVYyWVd4QmJHZHZMblJsYzNRS0lDQWdJR2x1ZEdOZk1TQXZMeUF4Q2lBZ0lDQnlaWFIxY200S0Nnb3ZMeUIwWlhOMGN5OWhjSEJ5YjNaaGJITXZjMmx1WjJ4bExXVjJZV3d1WVd4bmJ5NTBjem82VTJsdVoyeGxSWFpoYkVGc1oyOHVZU2dwSUMwK0lHSjVkR1Z6T2dwaE9nb2dJQ0FnWWlCaFgySnNiMk5yUURBS0NtRmZZbXh2WTJ0QU1Eb0tJQ0FnSUM4dklIUmxjM1J6TDJGd2NISnZkbUZzY3k5emFXNW5iR1V0WlhaaGJDNWhiR2R2TG5Sek9qZ0tJQ0FnSUM4dklIUm9hWE11YlhsVGRHRjBaUzUyWVd4MVpTQXJQU0F4Q2lBZ0lDQnBiblJqWHpBZ0x5OGdNQW9nSUNBZ0x5OGdkR1Z6ZEhNdllYQndjbTkyWVd4ekwzTnBibWRzWlMxbGRtRnNMbUZzWjI4dWRITTZOUW9nSUNBZ0x5OGdiWGxUZEdGMFpTQTlJRWRzYjJKaGJGTjBZWFJsUEhWcGJuUTJORDRvS1FvZ0lDQWdZbmwwWldOZk1DQXZMeUFpYlhsVGRHRjBaU0lLSUNBZ0lDOHZJSFJsYzNSekwyRndjSEp2ZG1Gc2N5OXphVzVuYkdVdFpYWmhiQzVoYkdkdkxuUnpPamdLSUNBZ0lDOHZJSFJvYVhNdWJYbFRkR0YwWlM1MllXeDFaU0FyUFNBeENpQWdJQ0JoY0hCZloyeHZZbUZzWDJkbGRGOWxlQW9nSUNBZ1lYTnpaWEowSUM4dklHTm9aV05ySUVkc2IySmhiRk4wWVhSbElHVjRhWE4wY3dvZ0lDQWdhVzUwWTE4eElDOHZJREVLSUNBZ0lDc0tJQ0FnSUM4dklIUmxjM1J6TDJGd2NISnZkbUZzY3k5emFXNW5iR1V0WlhaaGJDNWhiR2R2TG5Sek9qVUtJQ0FnSUM4dklHMTVVM1JoZEdVZ1BTQkhiRzlpWVd4VGRHRjBaVHgxYVc1ME5qUStLQ2tLSUNBZ0lHSjVkR1ZqWHpBZ0x5OGdJbTE1VTNSaGRHVWlDaUFnSUNBdkx5QjBaWE4wY3k5aGNIQnliM1poYkhNdmMybHVaMnhsTFdWMllXd3VZV3huYnk1MGN6bzRDaUFnSUNBdkx5QjBhR2x6TG0xNVUzUmhkR1V1ZG1Gc2RXVWdLejBnTVFvZ0lDQWdkVzVqYjNabGNpQXhDaUFnSUNCaGNIQmZaMnh2WW1Gc1gzQjFkQW9nSUNBZ0x5OGdkR1Z6ZEhNdllYQndjbTkyWVd4ekwzTnBibWRzWlMxbGRtRnNMbUZzWjI4dWRITTZPUW9nSUNBZ0x5OGdjbVYwZFhKdUlDZGhKd29nSUNBZ1lubDBaV05mTVNBdkx5QWlZU0lLSUNBZ0lISmxkSE4xWWdvS0NpOHZJSFJsYzNSekwyRndjSEp2ZG1Gc2N5OXphVzVuYkdVdFpYWmhiQzVoYkdkdkxuUnpPanBUYVc1bmJHVkZkbUZzUVd4bmJ5NWlLQ2tnTFQ0Z1lubDBaWE02Q21JNkNpQWdJQ0JpSUdKZllteHZZMnRBTUFvS1lsOWliRzlqYTBBd09nb2dJQ0FnTHk4Z2RHVnpkSE12WVhCd2NtOTJZV3h6TDNOcGJtZHNaUzFsZG1Gc0xtRnNaMjh1ZEhNNk1UTUtJQ0FnSUM4dklISmxkSFZ5YmlBbllpY0tJQ0FnSUhCMWMyaGllWFJsY3lBaVlpSUtJQ0FnSUhKbGRITjFZZ29LQ2k4dklIUmxjM1J6TDJGd2NISnZkbUZzY3k5emFXNW5iR1V0WlhaaGJDNWhiR2R2TG5Sek9qcFRhVzVuYkdWRmRtRnNRV3huYnk1MFpYTjBLQ2tnTFQ0Z2RtOXBaRG9LZEdWemRITXZZWEJ3Y205MllXeHpMM05wYm1kc1pTMWxkbUZzTG1Gc1oyOHVkSE02T2xOcGJtZHNaVVYyWVd4QmJHZHZMblJsYzNRNkNpQWdJQ0F2THlCMFpYTjBjeTloY0hCeWIzWmhiSE12YzJsdVoyeGxMV1YyWVd3dVlXeG5ieTUwY3pveE5nb2dJQ0FnTHk4Z2RHVnpkQ2dwSUhzS0lDQWdJSEJ5YjNSdklEQWdNQW9nSUNBZ2FXNTBZMTh3SUM4dklEQUtJQ0FnSUdJZ2RHVnpkSE12WVhCd2NtOTJZV3h6TDNOcGJtZHNaUzFsZG1Gc0xtRnNaMjh1ZEhNNk9sTnBibWRzWlVWMllXeEJiR2R2TG5SbGMzUmZZbXh2WTJ0QU1Bb0tkR1Z6ZEhNdllYQndjbTkyWVd4ekwzTnBibWRzWlMxbGRtRnNMbUZzWjI4dWRITTZPbE5wYm1kc1pVVjJZV3hCYkdkdkxuUmxjM1JmWW14dlkydEFNRG9LSUNBZ0lDOHZJSFJsYzNSekwyRndjSEp2ZG1Gc2N5OXphVzVuYkdVdFpYWmhiQzVoYkdkdkxuUnpPalVLSUNBZ0lDOHZJRzE1VTNSaGRHVWdQU0JIYkc5aVlXeFRkR0YwWlR4MWFXNTBOalErS0NrS0lDQWdJR0o1ZEdWalh6QWdMeThnSW0xNVUzUmhkR1VpQ2lBZ0lDQXZMeUIwWlhOMGN5OWhjSEJ5YjNaaGJITXZjMmx1WjJ4bExXVjJZV3d1WVd4bmJ5NTBjem94TndvZ0lDQWdMeThnZEdocGN5NXRlVk4wWVhSbExuWmhiSFZsSUQwZ01Bb2dJQ0FnYVc1MFkxOHdJQzh2SURBS0lDQWdJR0Z3Y0Y5bmJHOWlZV3hmY0hWMENpQWdJQ0F2THlCMFpYTjBjeTloY0hCeWIzWmhiSE12YzJsdVoyeGxMV1YyWVd3dVlXeG5ieTUwY3pveE9Bb2dJQ0FnTHk4Z1kyOXVjM1FnY21WemRXeDBJRDBnZEdocGN5NWhLQ2tnZkh3Z2RHaHBjeTVpS0NrS0lDQWdJR05oYkd4emRXSWdZUW9nSUNBZ1pIVndDaUFnSUNCc1pXNEtJQ0FnSUdKNklIUmxjM1J6TDJGd2NISnZkbUZzY3k5emFXNW5iR1V0WlhaaGJDNWhiR2R2TG5Sek9qcFRhVzVuYkdWRmRtRnNRV3huYnk1MFpYTjBYM1JsY201aGNubGZabUZzYzJWQU1nb2dJQ0FnWWlCMFpYTjBjeTloY0hCeWIzWmhiSE12YzJsdVoyeGxMV1YyWVd3dVlXeG5ieTUwY3pvNlUybHVaMnhsUlhaaGJFRnNaMjh1ZEdWemRGOTBaWEp1WVhKNVgzUnlkV1ZBTVFvS2RHVnpkSE12WVhCd2NtOTJZV3h6TDNOcGJtZHNaUzFsZG1Gc0xtRnNaMjh1ZEhNNk9sTnBibWRzWlVWMllXeEJiR2R2TG5SbGMzUmZkR1Z5Ym1GeWVWOTBjblZsUURFNkNpQWdJQ0F2THlCMFpYTjBjeTloY0hCeWIzWmhiSE12YzJsdVoyeGxMV1YyWVd3dVlXeG5ieTUwY3pveE9Bb2dJQ0FnTHk4Z1kyOXVjM1FnY21WemRXeDBJRDBnZEdocGN5NWhLQ2tnZkh3Z2RHaHBjeTVpS0NrS0lDQWdJR1p5WVcxbFgyUnBaeUF4Q2lBZ0lDQm1jbUZ0WlY5aWRYSjVJREFLSUNBZ0lHSWdkR1Z6ZEhNdllYQndjbTkyWVd4ekwzTnBibWRzWlMxbGRtRnNMbUZzWjI4dWRITTZPbE5wYm1kc1pVVjJZV3hCYkdkdkxuUmxjM1JmZEdWeWJtRnllVjl0WlhKblpVQXpDZ3AwWlhOMGN5OWhjSEJ5YjNaaGJITXZjMmx1WjJ4bExXVjJZV3d1WVd4bmJ5NTBjem82VTJsdVoyeGxSWFpoYkVGc1oyOHVkR1Z6ZEY5MFpYSnVZWEo1WDIxbGNtZGxRRE02Q2lBZ0lDQXZMeUIwWlhOMGN5OWhjSEJ5YjNaaGJITXZjMmx1WjJ4bExXVjJZV3d1WVd4bmJ5NTBjem94T0FvZ0lDQWdMeThnWTI5dWMzUWdjbVZ6ZFd4MElEMGdkR2hwY3k1aEtDa2dmSHdnZEdocGN5NWlLQ2tLSUNBZ0lHWnlZVzFsWDJScFp5QXdDaUFnSUNBdkx5QjBaWE4wY3k5aGNIQnliM1poYkhNdmMybHVaMnhsTFdWMllXd3VZV3huYnk1MGN6b3hPUW9nSUNBZ0x5OGdZWE56WlhKMEtIUm9hWE11YlhsVGRHRjBaUzUyWVd4MVpTQTlQVDBnTVN3Z0oyRW9LU0J6YUc5MWJHUWdiMjVzZVNCaVpTQmpZV3hzWldRZ2IyNWpaU2NwQ2lBZ0lDQnBiblJqWHpBZ0x5OGdNQW9nSUNBZ0x5OGdkR1Z6ZEhNdllYQndjbTkyWVd4ekwzTnBibWRzWlMxbGRtRnNMbUZzWjI4dWRITTZOUW9nSUNBZ0x5OGdiWGxUZEdGMFpTQTlJRWRzYjJKaGJGTjBZWFJsUEhWcGJuUTJORDRvS1FvZ0lDQWdZbmwwWldOZk1DQXZMeUFpYlhsVGRHRjBaU0lLSUNBZ0lDOHZJSFJsYzNSekwyRndjSEp2ZG1Gc2N5OXphVzVuYkdVdFpYWmhiQzVoYkdkdkxuUnpPakU1Q2lBZ0lDQXZMeUJoYzNObGNuUW9kR2hwY3k1dGVWTjBZWFJsTG5aaGJIVmxJRDA5UFNBeExDQW5ZU2dwSUhOb2IzVnNaQ0J2Ym14NUlHSmxJR05oYkd4bFpDQnZibU5sSnlrS0lDQWdJR0Z3Y0Y5bmJHOWlZV3hmWjJWMFgyVjRDaUFnSUNCaGMzTmxjblFnTHk4Z1kyaGxZMnNnUjJ4dlltRnNVM1JoZEdVZ1pYaHBjM1J6Q2lBZ0lDQnBiblJqWHpFZ0x5OGdNUW9nSUNBZ1BUMEtJQ0FnSUdGemMyVnlkQ0F2THlCaEtDa2djMmh2ZFd4a0lHOXViSGtnWW1VZ1kyRnNiR1ZrSUc5dVkyVUtJQ0FnSUM4dklIUmxjM1J6TDJGd2NISnZkbUZzY3k5emFXNW5iR1V0WlhaaGJDNWhiR2R2TG5Sek9qSXdDaUFnSUNBdkx5QmhjM05sY25Rb2NtVnpkV3gwSUQwOVBTQW5ZU2NzSUNkU1pYTjFiSFFnYzJodmRXeGtJR0psSUNKaElpY3BDaUFnSUNCaWVYUmxZMTh4SUM4dklDSmhJZ29nSUNBZ1BUMEtJQ0FnSUdGemMyVnlkQ0F2THlCU1pYTjFiSFFnYzJodmRXeGtJR0psSUNKaElnb2dJQ0FnY21WMGMzVmlDZ3AwWlhOMGN5OWhjSEJ5YjNaaGJITXZjMmx1WjJ4bExXVjJZV3d1WVd4bmJ5NTBjem82VTJsdVoyeGxSWFpoYkVGc1oyOHVkR1Z6ZEY5MFpYSnVZWEo1WDJaaGJITmxRREk2Q2lBZ0lDQXZMeUIwWlhOMGN5OWhjSEJ5YjNaaGJITXZjMmx1WjJ4bExXVjJZV3d1WVd4bmJ5NTBjem94T0FvZ0lDQWdMeThnWTI5dWMzUWdjbVZ6ZFd4MElEMGdkR2hwY3k1aEtDa2dmSHdnZEdocGN5NWlLQ2tLSUNBZ0lHTmhiR3h6ZFdJZ1lnb2dJQ0FnWm5KaGJXVmZZblZ5ZVNBd0NpQWdJQ0JpSUhSbGMzUnpMMkZ3Y0hKdmRtRnNjeTl6YVc1bmJHVXRaWFpoYkM1aGJHZHZMblJ6T2pwVGFXNW5iR1ZGZG1Gc1FXeG5ieTUwWlhOMFgzUmxjbTVoY25sZmJXVnlaMlZBTXdvS0NpOHZJSFJsYzNSekwyRndjSEp2ZG1Gc2N5OXphVzVuYkdVdFpYWmhiQzVoYkdkdkxuUnpPanBUYVc1bmJHVkZkbUZzUVd4bmJ5NWZYMkZzWjI5MGMxOWZMbVJsWm1GMWJIUkRjbVZoZEdVb0tTQXRQaUIyYjJsa09ncGZYMkZzWjI5MGMxOWZMbVJsWm1GMWJIUkRjbVZoZEdVNkNpQWdJQ0JpSUY5ZllXeG5iM1J6WDE4dVpHVm1ZWFZzZEVOeVpXRjBaVjlpYkc5amEwQXdDZ3BmWDJGc1oyOTBjMTlmTG1SbFptRjFiSFJEY21WaGRHVmZZbXh2WTJ0QU1Eb0tJQ0FnSUhKbGRITjFZZ289IiwiY2xlYXIiOiJJM0J5WVdkdFlTQjJaWEp6YVc5dUlERXhDaU53Y21GbmJXRWdkSGx3WlhSeVlXTnJJR1poYkhObENnb3ZMeUJBWVd4bmIzSmhibVJtYjNWdVpHRjBhVzl1TDJGc1oyOXlZVzVrTFhSNWNHVnpZM0pwY0hRdlltRnpaUzFqYjI1MGNtRmpkQzVrTG5Sek9qcENZWE5sUTI5dWRISmhZM1F1WTJ4bFlYSlRkR0YwWlZCeWIyZHlZVzBvS1NBdFBpQjFhVzUwTmpRNkNtMWhhVzQ2Q2lBZ0lDQmlJRzFoYVc1ZllteHZZMnRBTUFvS2JXRnBibDlpYkc5amEwQXdPZ29nSUNBZ2NIVnphR2x1ZENBeENpQWdJQ0J5WlhSMWNtNEsifSwiYnl0ZUNvZGUiOnsiYXBwcm92YWwiOiJDeUFDQUFFbUFnZHRlVk4wWVhSbEFXRkNBQUJDQUFBeEd5SVRRUUFwUWdBQU5ob0FnQVNuZ0FEZVR3R09BUUFIUWdBQVFnQUFBREVaSWhJeEdDSVRFRVNJQUJKQy8rd3hHU0lTTVJnaUVoQkVpQUJSSTBOQ0FBQ0lBQmdqUTBJQUFDSW9aVVFqQ0NoUEFXY3BpVUlBQUlBQllvbUtBQUFpUWdBQUtDSm5pUC9kU1JWQkFCZENBQUNMQVl3QVFnQUFpd0FpS0dWRUl4SkVLUkpFaVlqL3pZd0FRdi9yUWdBQWlRPT0iLCJjbGVhciI6IkMwSUFBSUVCUXc9PSJ9LCJjb21waWxlckluZm8iOnsiY29tcGlsZXIiOiJwdXlhIiwiY29tcGlsZXJWZXJzaW9uIjp7Im1ham9yIjo1LCJtaW5vciI6OSwicGF0Y2giOjAsImNvbW1pdEhhc2giOm51bGx9fSwiZXZlbnRzIjpbXSwidGVtcGxhdGVWYXJpYWJsZXMiOnt9LCJzY3JhdGNoVmFyaWFibGVzIjp7fX0=";
    }

}
