[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "arc56-generated-janak_d87fd868"
version = "1.1.2026082408"
description = "Generated ARC-56 Algorand smart-contract clients for Janakiraman1021/algo."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Janakiraman1021" }]
keywords = ["algorand", "arc56", "avm", "smart-contract", "generated-client", "Janakiraman1021", "algo"]
dependencies = [
    "algokit-utils>=4.2.3,<5.0.0",
    "py-algorand-sdk>=2.11.1,<3.0.0",
]

[project.urls]
Homepage = "https://github.com/scholtz/Arc56Registry"
Repository = "https://github.com/scholtz/Arc56Registry"

[tool.hatch.build.targets.wheel]
packages = ["src/arc56_generated_janak_d87fd868"]
