/* eslint-disable */
/**
 * This file was automatically generated by @algorandfoundation/algokit-client-generator.
 * DO NOT MODIFY IT BY HAND.
 * requires: @algorandfoundation/algokit-utils: ^7
 */
import { type AlgorandClient } from '@algorandfoundation/algokit-utils/types/algorand-client'
import { ABIReturn, AppReturn, SendAppTransactionResult } from '@algorandfoundation/algokit-utils/types/app'
import { Arc56Contract, getArc56ReturnValue, getABIStructFromABITuple } from '@algorandfoundation/algokit-utils/types/app-arc56'
import {
  AppClient as _AppClient,
  AppClientMethodCallParams,
  AppClientParams,
  AppClientBareCallParams,
  CallOnComplete,
  AppClientCompilationParams,
  ResolveAppClientByCreatorAndName,
  ResolveAppClientByNetwork,
  CloneAppClientParams,
} from '@algorandfoundation/algokit-utils/types/app-client'

import { TransactionComposer, AppCallMethodCall, AppMethodCallTransactionArgument, SimulateOptions, RawSimulateOptions, SkipSignaturesSimulateOptions } from '@algorandfoundation/algokit-utils/types/composer'
import { SendParams, SendSingleTransactionResult, SendAtomicTransactionComposerResults } from '@algorandfoundation/algokit-utils/types/transaction'
import { Address, encodeAddress, modelsv2, OnApplicationComplete, Transaction, TransactionSigner } from 'algosdk'

export const APP_SPEC: Arc56Contract = {"name":"SpokeUtilsWrapper","structs":{},"methods":[{"name":"toValue","args":[{"type":"uint256","name":"__arc4_amount"},{"type":"uint256","name":"__arc4_decimals"},{"type":"uint256","name":"__arc4_price"}],"returns":{"type":"uint256"},"actions":{"create":[],"call":["NoOp"]},"readonly":true,"events":[],"recommendations":{}}],"arcs":[22,28],"networks":{},"state":{"schema":{"global":{"ints":0,"bytes":0},"local":{"ints":0,"bytes":0}},"keys":{"global":{},"local":{},"box":{}},"maps":{"global":{},"local":{},"box":{}}},"bareActions":{"create":[],"call":[]},"sourceInfo":{"approval":{"sourceInfo":[{"pc":[134,144,154],"errorMessage":"invalid number of bytes for arc4.uint256"},{"pc":[167],"errorMessage":"not payable"},{"pc":[181],"errorMessage":"overflow"},{"pc":[262],"errorMessage":"underflow"}],"pcOffsetMethod":"none"},"clear":{"sourceInfo":[],"pcOffsetMethod":"none"}},"events":[]} as unknown as Arc56Contract

/**
 * A state record containing binary data
 */
export interface BinaryState {
  /**
   * Gets the state value as a Uint8Array
   */
  asByteArray(): Uint8Array | undefined
  /**
   * Gets the state value as a string
   */
  asString(): string | undefined
}

class BinaryStateValue implements BinaryState {
  constructor(private value: Uint8Array | undefined) {}

  asByteArray(): Uint8Array | undefined {
    return this.value
  }

  asString(): string | undefined {
    return this.value !== undefined ? Buffer.from(this.value).toString('utf-8') : undefined
  }
}

/**
 * Expands types for IntelliSense so they are more human readable
 * See https://stackoverflow.com/a/69288824
 */
export type Expand<T> = T extends (...args: infer A) => infer R
  ? (...args: Expand<A>) => Expand<R>
  : T extends infer O
    ? { [K in keyof O]: O[K] }
    : never


/**
 * The argument types for the SpokeUtilsWrapper contract
 */
export type SpokeUtilsWrapperArgs = {
  /**
   * The object representation of the arguments for each method
   */
  obj: {
    'toValue(uint256,uint256,uint256)uint256': {
      __arc4Amount: bigint | number
      __arc4Decimals: bigint | number
      __arc4Price: bigint | number
    }
  }
  /**
   * The tuple representation of the arguments for each method
   */
  tuple: {
    'toValue(uint256,uint256,uint256)uint256': [__arc4Amount: bigint | number, __arc4Decimals: bigint | number, __arc4Price: bigint | number]
  }
}

/**
 * The return type for each method
 */
export type SpokeUtilsWrapperReturns = {
  'toValue(uint256,uint256,uint256)uint256': bigint
}

/**
 * Defines the types of available calls and state of the SpokeUtilsWrapper smart contract.
 */
export type SpokeUtilsWrapperTypes = {
  /**
   * Maps method signatures / names to their argument and return types.
   */
  methods:
    & Record<'toValue(uint256,uint256,uint256)uint256' | 'toValue', {
      argsObj: SpokeUtilsWrapperArgs['obj']['toValue(uint256,uint256,uint256)uint256']
      argsTuple: SpokeUtilsWrapperArgs['tuple']['toValue(uint256,uint256,uint256)uint256']
      returns: SpokeUtilsWrapperReturns['toValue(uint256,uint256,uint256)uint256']
    }>
}

/**
 * Defines the possible abi call signatures.
 */
export type SpokeUtilsWrapperSignatures = keyof SpokeUtilsWrapperTypes['methods']
/**
 * Defines the possible abi call signatures for methods that return a non-void value.
 */
export type SpokeUtilsWrapperNonVoidMethodSignatures = keyof SpokeUtilsWrapperTypes['methods'] extends infer T ? T extends keyof SpokeUtilsWrapperTypes['methods'] ? MethodReturn<T> extends void ? never : T  : never : never
/**
 * Defines an object containing all relevant parameters for a single call to the contract.
 */
export type CallParams<TArgs> = Expand<
  Omit<AppClientMethodCallParams, 'method' | 'args' | 'onComplete'> &
    {
      /** The args for the ABI method call, either as an ordered array or an object */
      args: Expand<TArgs>
    }
>
/**
 * Maps a method signature from the SpokeUtilsWrapper smart contract to the method's arguments in either tuple or struct form
 */
export type MethodArgs<TSignature extends SpokeUtilsWrapperSignatures> = SpokeUtilsWrapperTypes['methods'][TSignature]['argsObj' | 'argsTuple']
/**
 * Maps a method signature from the SpokeUtilsWrapper smart contract to the method's return type
 */
export type MethodReturn<TSignature extends SpokeUtilsWrapperSignatures> = SpokeUtilsWrapperTypes['methods'][TSignature]['returns']



/**
 * Exposes methods for constructing `AppClient` params objects for ABI calls to the SpokeUtilsWrapper smart contract
 */
export abstract class SpokeUtilsWrapperParamsFactory {
  /**
   * Constructs a no op call for the toValue(uint256,uint256,uint256)uint256 ABI method
   *
   * @param params Parameters for the call
   * @returns An `AppClientMethodCallParams` object for the call
   */
  static toValue(params: CallParams<SpokeUtilsWrapperArgs['obj']['toValue(uint256,uint256,uint256)uint256'] | SpokeUtilsWrapperArgs['tuple']['toValue(uint256,uint256,uint256)uint256']> & CallOnComplete): AppClientMethodCallParams & CallOnComplete {
    return {
      ...params,
      method: 'toValue(uint256,uint256,uint256)uint256' as const,
      args: Array.isArray(params.args) ? params.args : [params.args.__arc4Amount, params.args.__arc4Decimals, params.args.__arc4Price],
    }
  }
}

/**
 * A client to make calls to the SpokeUtilsWrapper smart contract
 */
export class SpokeUtilsWrapperClient {
  /**
   * The underlying `AppClient` for when you want to have more flexibility
   */
  public readonly appClient: _AppClient

  /**
   * Creates a new instance of `SpokeUtilsWrapperClient`
   *
   * @param appClient An `AppClient` instance which has been created with the SpokeUtilsWrapper app spec
   */
  constructor(appClient: _AppClient)
  /**
   * Creates a new instance of `SpokeUtilsWrapperClient`
   *
   * @param params The parameters to initialise the app client with
   */
  constructor(params: Omit<AppClientParams, 'appSpec'>)
  constructor(appClientOrParams: _AppClient | Omit<AppClientParams, 'appSpec'>) {
    this.appClient = appClientOrParams instanceof _AppClient ? appClientOrParams : new _AppClient({
      ...appClientOrParams,
      appSpec: APP_SPEC,
    })
  }

  /**
   * Checks for decode errors on the given return value and maps the return value to the return type for the given method
   * @returns The typed return value or undefined if there was no value
   */
  decodeReturnValue<TSignature extends SpokeUtilsWrapperNonVoidMethodSignatures>(method: TSignature, returnValue: ABIReturn | undefined) {
    return returnValue !== undefined ? getArc56ReturnValue<MethodReturn<TSignature>>(returnValue, this.appClient.getABIMethod(method), APP_SPEC.structs) : undefined
  }

  /**
   * Returns a new `SpokeUtilsWrapperClient` client, resolving the app by creator address and name
   * using AlgoKit app deployment semantics (i.e. looking for the app creation transaction note).
   * @param params The parameters to create the app client
   */
  public static async fromCreatorAndName(params: Omit<ResolveAppClientByCreatorAndName, 'appSpec'>): Promise<SpokeUtilsWrapperClient> {
    return new SpokeUtilsWrapperClient(await _AppClient.fromCreatorAndName({...params, appSpec: APP_SPEC}))
  }
  
  /**
   * Returns an `SpokeUtilsWrapperClient` instance for the current network based on
   * pre-determined network-specific app IDs specified in the ARC-56 app spec.
   *
   * If no IDs are in the app spec or the network isn't recognised, an error is thrown.
   * @param params The parameters to create the app client
   */
  static async fromNetwork(
    params: Omit<ResolveAppClientByNetwork, 'appSpec'>
  ): Promise<SpokeUtilsWrapperClient> {
    return new SpokeUtilsWrapperClient(await _AppClient.fromNetwork({...params, appSpec: APP_SPEC}))
  }
  
  /** The ID of the app instance this client is linked to. */
  public get appId() {
    return this.appClient.appId
  }
  
  /** The app address of the app instance this client is linked to. */
  public get appAddress() {
    return this.appClient.appAddress
  }
  
  /** The name of the app. */
  public get appName() {
    return this.appClient.appName
  }
  
  /** The ARC-56 app spec being used */
  public get appSpec() {
    return this.appClient.appSpec
  }
  
  /** A reference to the underlying `AlgorandClient` this app client is using. */
  public get algorand(): AlgorandClient {
    return this.appClient.algorand
  }

  /**
   * Get parameters to create transactions for the current app. A good mental model for this is that these parameters represent a deferred transaction creation.
   */
  readonly params = {
    /**
     * Makes a clear_state call to an existing instance of the SpokeUtilsWrapper smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams>) => {
      return this.appClient.params.bare.clearState(params)
    },

    /**
     * Makes a call to the SpokeUtilsWrapper smart contract using the `toValue(uint256,uint256,uint256)uint256` ABI method.
     * 
     * This method is a readonly method; calling it with onComplete of NoOp will result in a simulated transaction rather than a real transaction.
     *
     * @param params The params for the smart contract call
     * @returns The call params
     */
    toValue: (params: CallParams<SpokeUtilsWrapperArgs['obj']['toValue(uint256,uint256,uint256)uint256'] | SpokeUtilsWrapperArgs['tuple']['toValue(uint256,uint256,uint256)uint256']> & {onComplete?: OnApplicationComplete.NoOpOC}) => {
      return this.appClient.params.call(SpokeUtilsWrapperParamsFactory.toValue(params))
    },

  }

  /**
   * Create transactions for the current app
   */
  readonly createTransaction = {
    /**
     * Makes a clear_state call to an existing instance of the SpokeUtilsWrapper smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams>) => {
      return this.appClient.createTransaction.bare.clearState(params)
    },

    /**
     * Makes a call to the SpokeUtilsWrapper smart contract using the `toValue(uint256,uint256,uint256)uint256` ABI method.
     * 
     * This method is a readonly method; calling it with onComplete of NoOp will result in a simulated transaction rather than a real transaction.
     *
     * @param params The params for the smart contract call
     * @returns The call transaction
     */
    toValue: (params: CallParams<SpokeUtilsWrapperArgs['obj']['toValue(uint256,uint256,uint256)uint256'] | SpokeUtilsWrapperArgs['tuple']['toValue(uint256,uint256,uint256)uint256']> & {onComplete?: OnApplicationComplete.NoOpOC}) => {
      return this.appClient.createTransaction.call(SpokeUtilsWrapperParamsFactory.toValue(params))
    },

  }

  /**
   * Send calls to the current app
   */
  readonly send = {
    /**
     * Makes a clear_state call to an existing instance of the SpokeUtilsWrapper smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams & SendParams>) => {
      return this.appClient.send.bare.clearState(params)
    },

    /**
     * Makes a call to the SpokeUtilsWrapper smart contract using the `toValue(uint256,uint256,uint256)uint256` ABI method.
     * 
     * This method is a readonly method; calling it with onComplete of NoOp will result in a simulated transaction rather than a real transaction.
     *
     * @param params The params for the smart contract call
     * @returns The call result
     */
    toValue: async (params: CallParams<SpokeUtilsWrapperArgs['obj']['toValue(uint256,uint256,uint256)uint256'] | SpokeUtilsWrapperArgs['tuple']['toValue(uint256,uint256,uint256)uint256']> & SendParams & {onComplete?: OnApplicationComplete.NoOpOC}) => {
      const result = await this.appClient.send.call(SpokeUtilsWrapperParamsFactory.toValue(params))
      return {...result, return: result.return as unknown as (undefined | SpokeUtilsWrapperReturns['toValue(uint256,uint256,uint256)uint256'])}
    },

  }

  /**
   * Clone this app client with different params
   *
   * @param params The params to use for the the cloned app client. Omit a param to keep the original value. Set a param to override the original value. Setting to undefined will clear the original value.
   * @returns A new app client with the altered params
   */
  public clone(params: CloneAppClientParams) {
    return new SpokeUtilsWrapperClient(this.appClient.clone(params))
  }

  /**
   * Makes a readonly (simulated) call to the SpokeUtilsWrapper smart contract using the `toValue(uint256,uint256,uint256)uint256` ABI method.
   * 
   * This method is a readonly method; calling it with onComplete of NoOp will result in a simulated transaction rather than a real transaction.
   *
   * @param params The params for the smart contract call
   * @returns The call result
   */
  async toValue(params: CallParams<SpokeUtilsWrapperArgs['obj']['toValue(uint256,uint256,uint256)uint256'] | SpokeUtilsWrapperArgs['tuple']['toValue(uint256,uint256,uint256)uint256']>) {
    const result = await this.appClient.send.call(SpokeUtilsWrapperParamsFactory.toValue(params))
    return result.return as unknown as SpokeUtilsWrapperReturns['toValue(uint256,uint256,uint256)uint256']
  }

  /**
   * Methods to access state for the current SpokeUtilsWrapper app
   */
  state = {
  }

  public newGroup(): SpokeUtilsWrapperComposer {
    const client = this
    const composer = this.algorand.newGroup()
    let promiseChain:Promise<unknown> = Promise.resolve()
    const resultMappers: Array<undefined | ((x: ABIReturn | undefined) => any)> = []
    return {
      /**
       * Add a toValue(uint256,uint256,uint256)uint256 method call against the SpokeUtilsWrapper contract
       */
      toValue(params: CallParams<SpokeUtilsWrapperArgs['obj']['toValue(uint256,uint256,uint256)uint256'] | SpokeUtilsWrapperArgs['tuple']['toValue(uint256,uint256,uint256)uint256']> & {onComplete?: OnApplicationComplete.NoOpOC}) {
        promiseChain = promiseChain.then(async () => composer.addAppCallMethodCall(await client.params.toValue(params)))
        resultMappers.push((v) => client.decodeReturnValue('toValue(uint256,uint256,uint256)uint256', v))
        return this
      },
      /**
       * Add a clear state call to the SpokeUtilsWrapper contract
       */
      clearState(params: AppClientBareCallParams) {
        promiseChain = promiseChain.then(() => composer.addAppCall(client.params.clearState(params)))
        return this
      },
      addTransaction(txn: Transaction, signer?: TransactionSigner) {
        promiseChain = promiseChain.then(() => composer.addTransaction(txn, signer))
        return this
      },
      async composer() {
        await promiseChain
        return composer
      },
      async simulate(options?: SimulateOptions) {
        await promiseChain
        const result = await (!options ? composer.simulate() : composer.simulate(options))
        return {
          ...result,
          returns: result.returns?.map((val, i) => resultMappers[i] !== undefined ? resultMappers[i]!(val) : val.returnValue)
        }
      },
      async send(params?: SendParams) {
        await promiseChain
        const result = await composer.send(params)
        return {
          ...result,
          returns: result.returns?.map((val, i) => resultMappers[i] !== undefined ? resultMappers[i]!(val) : val.returnValue)
        }
      }
    } as unknown as SpokeUtilsWrapperComposer
  }
}
export type SpokeUtilsWrapperComposer<TReturns extends [...any[]] = []> = {
  /**
   * Calls the toValue(uint256,uint256,uint256)uint256 ABI method.
   *
   * @param args The arguments for the contract call
   * @param params Any additional parameters for the call
   * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
   */
  toValue(params?: CallParams<SpokeUtilsWrapperArgs['obj']['toValue(uint256,uint256,uint256)uint256'] | SpokeUtilsWrapperArgs['tuple']['toValue(uint256,uint256,uint256)uint256']>): SpokeUtilsWrapperComposer<[...TReturns, SpokeUtilsWrapperReturns['toValue(uint256,uint256,uint256)uint256'] | undefined]>

  /**
   * Makes a clear_state call to an existing instance of the SpokeUtilsWrapper smart contract.
   *
   * @param args The arguments for the bare call
   * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
   */
  clearState(params?: AppClientBareCallParams): SpokeUtilsWrapperComposer<[...TReturns, undefined]>

  /**
   * Adds a transaction to the composer
   *
   * @param txn A transaction to add to the transaction group
   * @param signer The optional signer to use when signing this transaction.
   */
  addTransaction(txn: Transaction, signer?: TransactionSigner): SpokeUtilsWrapperComposer<TReturns>
  /**
   * Returns the underlying AtomicTransactionComposer instance
   */
  composer(): Promise<TransactionComposer>
  /**
   * Simulates the transaction group and returns the result
   */
  simulate(): Promise<SpokeUtilsWrapperComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  simulate(options: SkipSignaturesSimulateOptions): Promise<SpokeUtilsWrapperComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  simulate(options: RawSimulateOptions): Promise<SpokeUtilsWrapperComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  /**
   * Sends the transaction group to the network and returns the results
   */
  send(params?: SendParams): Promise<SpokeUtilsWrapperComposerResults<TReturns>>
}
export type SpokeUtilsWrapperComposerResults<TReturns extends [...any[]]> = Expand<SendAtomicTransactionComposerResults & {
  returns: TReturns
}>

